Request to iamoracle as a delegate
celo-org/celo-mondo pull request #22
Opened 2024-08-07 20:58 UTC by iamoracle

2024-08-09 10:34 UTC, aaronmgdr requested changes

2024-08-09 10:34 UTC, aaronmgdr commented on src/config/delegates.json
> +    "logoUri": "/logos/delegatees/iamoracle.jpeg",
file is png but this is jpeg

2024-08-09 11:40 UTC, iamoracle reviewed
Fixed

2024-08-09 12:15 UTC, aaronmgdr commented
hmm when i visit preview your logo does not show. im not sure why.

2024-08-10 09:54 UTC, iamoracle commented
Fixed now @aaronmgdr

2024-08-10 18:39 UTC, jmrossy approved these changes

2024-08-10 18:43 UTC, merged